config/routes.rb
AvtUnderground::Application.routes.draw do
  devise_for :users

  match "app.manifest" => "pages#manifest"

  root :to => 'pages#index'

  match 'app' => 'pages#app'

  resources :aircrafts do
    resources :positions
    resources :cg_entries
    resources :moment_entries
  end

  resources :positions
  resources :cg_entries
  resources :moment_entries

  resources :models

  namespace :admin do
    resources :organizations do
      member do
        get :use
      end
    end
  end

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  attr_accessible :tail_number,
                  :bow,
                  :moment

  attr_protected :updated_at, :created_at

  validates :tail_number, :presence => true

  validates :bow, :presence => true

  validates :moment, :presence => true
  
  belongs_to :organization
  belongs_to :model

  has_many :positions
  has_many :cg_entries
  has_many :moment_entries

  def cg
    "%0.2f" % (moment / bow * 1000)
  end

  def serializable_hash(options = {})
    hash_info = super(options)
    hash_info[:model_name] = model.name
    hash_info[:positions] = positions
    hash_info[:cg_entries] = cg_entries
    hash_info[:moment_entries] = moment_entries
    hash_info
  end
end

app/models/cg_entry.rb
class CgEntry < ActiveRecord::Base
  belongs_to :aircraft
end

app/models/model.rb
class Model < ActiveRecord::Base
  has_many :aircrafts

  belongs_to :organization
end

app/models/moment_entry.rb
class MomentEntry < ActiveRecord::Base
  belongs_to :aircraft
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :users
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :aircraft

  attr_accessible :name, :moment

  validates :name, :presence => true
  validates :moment, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  belongs_to :organization
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_filter :authenticate_user!

  # GET /models
  # GET /models.json
  def index
    @models = Model.where(:organization_id => current_organization)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/new
  # GET /models/new.json
  def new
    @model = Model.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/1/edit
  def edit
    @model = Model.find(params[:id])
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(params[:model])

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /models/1
  # PUT /models/1.json
  def update
    @model = Model.find(params[:id])

    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_for(@model) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<table>
  <tr>
    <th style="width:200px;">Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @models.each do |model| %>
  <tr>
    <td><%= model.name %></td>
    <td><%= link_to 'Show', model, :class => "btn" %></td>
    <td><%= link_to 'Edit', edit_model_path(model), :class => "btn" %></td>
    <td><%= link_to 'Destroy', model, confirm: 'Are you sure?', method: :delete, :class => "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Model', new_model_path, :class => "btn btn-success" %>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path, :class => "btn" %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @model.name %>
</p>


<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>