config/routes.rb
AvtUnderground::Application.routes.draw do
  devise_for :users

  match "app.manifest" => "pages#manifest"

  root :to => 'pages#index'

  match 'app' => 'pages#app'

  resources :aircrafts do
    resources :positions
    resources :cg_entries
    resources :moment_entries
  end

  resources :positions
  resources :cg_entries
  resources :moment_entries

  resources :models

  namespace :admin do
    resources :organizations do
      member do
        get :use
      end
    end
  end

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  attr_accessible :tail_number,
                  :bow,
                  :moment

  attr_protected :updated_at, :created_at

  validates :tail_number, :presence => true

  validates :bow, :presence => true

  validates :moment, :presence => true
  
  belongs_to :organization
  belongs_to :model

  has_many :positions
  has_many :cg_entries
  has_many :moment_entries

  def cg
    "%0.2f" % (moment / bow * 1000)
  end

  def serializable_hash(options = {})
    hash_info = super(options)
    hash_info[:model_name] = model.name
    hash_info[:positions] = positions
    hash_info[:cg_entries] = cg_entries
    hash_info[:moment_entries] = moment_entries
    hash_info
  end
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  def index
    @aircrafts = Aircraft.includes(:model)

    respond_to do |format|
      format.html # index.html.erb
      format.json do
        render :json => @aircrafts
      end
    end
  end

  def show
    @aircraft = Aircraft.find params[:id]
  end

  def new
    @aircraft = Aircraft.new
  end

  def create
    @aircraft = Aircraft.new(params[:aircraft])
    @aircraft.organization_id = current_organization

    if @aircraft.save
      redirect_to @aircraft
    else
      render 'new'
    end
  end

  def edit
    @aircraft = Aircraft.find params[:id]
    @action = "update"

    render 'new'
  end

  def update
    @aircraft = Aircraft.find params[:id]
    @aircraft.update_attributes(params[:aircraft])

    if @aircraft.save
      redirect_to @aircraft 
    else
      render 'new'
    end

  end

  def destroy
    @aircraft = Aircraft.find params[:id]

    @aircraft.destroy

    redirect_to aircrafts_path
  end
end

app/helpers/aircraft_helper.rb
module AircraftHelper
end

app/views/aircrafts/index.html.erb
<%= link_to "Add Aircraft", new_aircraft_path, :class => "btn btn-success add_button" %>
<div style="clear:both"></div>
<br/>
<table class="table table-bordered">
  <tr>
    <th>Tail Number</th>
    <th>BOW</th>
    <th>CG</th>
    <th>Moment</th>
    <th>Last Updated</th>
    <th></th>
  </tr>

  <% @aircrafts.each do |aircraft| %>
    <tr>
      <td><%= aircraft.tail_number %></td>
      <td><%= aircraft.bow %></td>
      <td><%= aircraft.cg %></td>
      <td><%= aircraft.moment %></td>
      <td><%= aircraft.updated_at.to_s %></td>
      <td>
        <%= link_to "Show", aircraft_path(aircraft), :class => "btn" %>
        <%= link_to "Edit", edit_aircraft_path(aircraft), :class => "btn" %>
        <%= link_to "Delete", aircraft_path(aircraft), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete this aircraft?" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/aircrafts/new.html.erb
<%= form_for @aircraft, :action => "create" do |f| %>
  <fieldset>
    <legend><%= @aircraft.new_record? ? "Create" : "Update" %> Aircraft</legend>
    <div class="control-group">
      <%= f.label :tail_number, "Tail Number", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :tail_number, :class => "input-xlarge" %>
        <p class="help-block">Tail number of the aircraft</p>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :bow, "BOW", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :bow, :class => "input-xlarge" %>
        <p class="help-block">Weight of aircraft</p>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :moment, "Moment", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :moment, :class => "input-xlarge" %>
        <p class="help-block">Moment of aircraft</p>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :model, "Model", :class => "control-label" %>
      <div class="controls">
        <%= f.select :model_id, Model.all.collect { |model| [ model.name, model.id ] } %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit :class => "btn btn-success" %>
      <%= link_to "Cancel", (@aircraft.new_record?) ? aircrafts_path : @aircraft, :class => "btn" %>
    </div>
  </fieldset>
<% end %>

app/views/aircrafts/show.html.erb
<h2 style="float:left">Aircraft: <%= @aircraft.tail_number %></h2>
<div style="float:right;">
  <%= link_to "Edit", edit_aircraft_path(@aircraft), :class => "btn" %>
  <%= link_to "Delete", aircraft_path(@aircraft), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete this aircraft?" %>
</div>
<div style="clear:both"></div>
<br/>
<p>BOW: <%= @aircraft.bow %></p>
<p>CG: <%= @aircraft.cg %></p>
<p>Moment: <%= @aircraft.moment %></p>
<p>Last Updated: <%= @aircraft.updated_at.to_s %></p>

<div style="width:49%;float:left">
  <h3 style="float:left">Positions</h3>
  <div style="float:right">
    <%= link_to "Add Position", new_aircraft_position_path(@aircraft), :class => "btn" %>
  </div>
  <div style="clear:both"></div>
  <br/>
  <table class="table table-bordered">
    <tr>
      <th>Name</th>
      <th style="width:80px"></th>
    </tr>
    <% @aircraft.positions.each do |position| %>
      <tr>
        <td><%= position.name %></td>
        <td>
          <%= link_to raw(icon("pencil", "")), edit_position_path(position), :class => "btn" %>
          <%= link_to raw(icon("remove")), position_path(position), :method => :destroy, :class => "btn btn-danger", :confirm => "Are you sure you want to delete this posiiton?" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<div style="width: 49%; margin-left: 8px; float:left">
  <h3 style="float:left">CG Table</h3>
  <div style="float:right">
    <%= link_to "Add Entry", new_aircraft_cg_entry_path(@aircraft), :class => "btn" %>
  </div>
  <div style="clear:both"></div>
  <br/>
  <table class="table table-bordered">
    <tr>
      <th>Weight</th>
      <th>Arm</th>
      <th style="width:80px"></th>
    </tr>

    <% @aircraft.cg_entries.each do |entry| %>
      <tr>
        <td><%= entry.weight %></td>
        <td><%= entry.arm %></td>
        <td>
          <%= link_to raw(icon("pencil", "")), edit_cg_entry_path(entry), :class => "btn" %>
          <%= link_to raw(icon("remove")), cg_entry_path(entry), :method => :destroy, :class => "btn btn-danger", :confirm => "Are you sure you want to delete this entry?" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<div style="clear:both;"></div>

<div style="width: 49%; float:left">
  <h3 style="float:left">Moment Table</h3>
  <div style="float:right">
    <%= link_to "Add Entry", new_aircraft_moment_entry_path(@aircraft), :class => "btn" %>
  </div>
  <div style="clear:both"></div>
  <br/>
  <table class="table table-bordered">
    <tr>
      <th>Weight</th>
      <th>Moment</th>
      <th style="width:80px"></th>
    </tr>

    <% @aircraft.moment_entries.each do |entry| %>
      <tr>
        <td><%= entry.weight %></td>
        <td><%= entry.moment %></td>
        <td>
          <%= link_to raw(icon("pencil", "")), edit_moment_entry_path(entry), :class => "btn" %>
          <%= link_to raw(icon("remove")), moment_entry_path(entry), :method => :destroy, :class => "btn btn-danger", :confirm => "Are you sure you want to delete this moment?" %>
        </td>
      </tr>
    <% end %>
  </table>  
</div>