config/routes.rb
AvtUnderground::Application.routes.draw do
  devise_for :users

  match "app.manifest" => "pages#manifest"

  root :to => 'pages#index'

  match 'app' => 'pages#app'

  resources :aircrafts do
    resources :positions
    resources :cg_entries
    resources :moment_entries
  end

  resources :positions
  resources :cg_entries
  resources :moment_entries

  resources :models

  namespace :admin do
    resources :organizations do
      member do
        get :use
      end
    end
  end

end

app/models/cg_entry.rb
class CgEntry < ActiveRecord::Base
  belongs_to :aircraft
end

app/controllers/cg_entries_controller.rb
class CgEntriesController < ApplicationController
  # GET /cg_entries
  # GET /cg_entries.json
  def index
    @cg_entries = CgEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cg_entries }
    end
  end

  # GET /cg_entries/1
  # GET /cg_entries/1.json
  def show
    @cg_entry = CgEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cg_entry }
    end
  end

  # GET /cg_entries/new
  # GET /cg_entries/new.json
  def new
    @cg_entry = CgEntry.new
    @aircraft = Aircraft.find(params[:aircraft_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cg_entry }
    end
  end

  # GET /cg_entries/1/edit
  def edit
    @cg_entry = CgEntry.find(params[:id])
    @aircraft = @cg_entry.aircraft
    @action = "update"
  end

  # POST /cg_entries
  # POST /cg_entries.json
  def create
    @cg_entry = CgEntry.new(params[:cg_entry])
    @aircraft = Aircraft.find(params[:aircraft_id])

    @cg_entry.aircraft_id = @aircraft

    respond_to do |format|
      if @cg_entry.save
        format.html { redirect_to @aircraft, notice: 'Cg entry was successfully created.' }
        format.json { render json: @cg_entry, status: :created, location: @cg_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @cg_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cg_entries/1
  # PUT /cg_entries/1.json
  def update
    @cg_entry = CgEntry.find(params[:id])

    respond_to do |format|
      if @cg_entry.update_attributes(params[:cg_entry])
        format.html { redirect_to @aircraft, notice: 'Cg entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cg_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cg_entries/1
  # DELETE /cg_entries/1.json
  def destroy
    @cg_entry = CgEntry.find(params[:id])
    @cg_entry.destroy

    respond_to do |format|
      format.html { redirect_to cg_entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cg_entries_helper.rb
module CgEntriesHelper
end

app/views/cg_entries/_form.html.erb
<%= form_for(@cg_entry, :url => (@action == "update") ? position_path(@position) : "/aircrafts/#{@aircraft.id}/cg_entries") do |f| %>
  <% if @cg_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cg_entry.errors.count, "error") %> prohibited this CG Entry from being saved:</h2>

      <ul>
      <% @cg_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :weight, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :weight, :class => "input-xlarge" %>
      <p class="help-block">Weight of the aircraft</p>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :arm, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :arm, :class => "input-xlarge" %>
      <p class="help-block">Arm of the aircraft</p>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
    <%= link_to "Cancel", aircraft_path(@aircraft), :class => "btn" %>
  </div>
<% end %>

app/views/cg_entries/edit.html.erb
<fieldset>
  <legend>Updating CG Entry</legend>
  <%= render 'form' %>
</fieldset>

app/views/cg_entries/index.html.erb
<h1>Listing cg_entries</h1>

<table>
  <tr>
    <th>Arm</th>
    <th>Moment</th>
    <th>Aircraft</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cg_entries.each do |cg_entry| %>
  <tr>
    <td><%= cg_entry.arm %></td>
    <td><%= cg_entry.moment %></td>
    <td><%= cg_entry.aircraft_id %></td>
    <td><%= link_to 'Show', cg_entry %></td>
    <td><%= link_to 'Edit', edit_cg_entry_path(cg_entry) %></td>
    <td><%= link_to 'Destroy', cg_entry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cg entry', new_cg_entry_path %>

app/views/cg_entries/new.html.erb
<fieldset>
  <legend>New CG Entry</legend>
  <%= render 'form' %>
</fieldset>

<%= link_to 'Back', cg_entries_path %>

app/views/cg_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Arm:</b>
  <%= @cg_entry.arm %>
</p>

<p>
  <b>Moment:</b>
  <%= @cg_entry.moment %>
</p>

<p>
  <b>Aircraft:</b>
  <%= @cg_entry.aircraft_id %>
</p>


<%= link_to 'Edit', edit_cg_entry_path(@cg_entry) %> |
<%= link_to 'Back', cg_entries_path %>