config/routes.rb
AvtUnderground::Application.routes.draw do
  devise_for :users

  match "app.manifest" => "pages#manifest"

  root :to => 'pages#index'

  match 'app' => 'pages#app'

  resources :aircrafts do
    resources :positions
    resources :cg_entries
    resources :moment_entries
  end

  resources :positions
  resources :cg_entries
  resources :moment_entries

  resources :models

  namespace :admin do
    resources :organizations do
      member do
        get :use
      end
    end
  end

end

app/models/moment_entry.rb
class MomentEntry < ActiveRecord::Base
  belongs_to :aircraft
end

app/controllers/moment_entries_controller.rb
class MomentEntriesController < ApplicationController
  # GET /moment_entries
  # GET /moment_entries.json
  def index
    @moment_entries = MomentEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moment_entries }
    end
  end

  # GET /moment_entries/1
  # GET /moment_entries/1.json
  def show
    @moment_entry = MomentEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @moment_entry }
    end
  end

  # GET /moment_entries/new
  # GET /moment_entries/new.json
  def new
    @moment_entry = MomentEntry.new
    @aircraft = Aircraft.find params[:aircraft_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @moment_entry }
    end
  end

  # GET /moment_entries/1/edit
  def edit
    @moment_entry = MomentEntry.find(params[:id])
    @aircraft = @moment_entry.aircraft

    @action = "update"
  end

  # POST /moment_entries
  # POST /moment_entries.json
  def create
    @moment_entry = MomentEntry.new(params[:moment_entry])
    @aircraft = Aircraft.find params[:aircraft_id]

    @moment_entry.aircraft_id = @aircraft.id

    respond_to do |format|
      if @moment_entry.save
        format.html { redirect_to @aircraft, notice: 'Moment entry was successfully created.' }
        format.json { render json: @moment_entry, status: :created, location: @moment_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @moment_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /moment_entries/1
  # PUT /moment_entries/1.json
  def update
    @moment_entry = MomentEntry.find(params[:id])

    respond_to do |format|
      if @moment_entry.update_attributes(params[:moment_entry])
        format.html { redirect_to @moment_entry.aircraft, notice: 'Moment entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @moment_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moment_entries/1
  # DELETE /moment_entries/1.json
  def destroy
    @moment_entry = MomentEntry.find(params[:id])
    @moment_entry.destroy

    respond_to do |format|
      format.html { redirect_to @moment_entry.aircraft }
      format.json { head :no_content }
    end
  end
end

app/helpers/moment_entries_helper.rb
module MomentEntriesHelper
end

app/views/moment_entries/_form.html.erb
<%= form_for(@moment_entry, :url => (@action == "update") ? moment_entry_path(@moment_entry) : "/aircrafts/#{@aircraft.id}/moment_entries") do |f| %>
  <% if @moment_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moment_entry.errors.count, "error") %> prohibited this moment_entry from being saved:</h2>

      <ul>
      <% @moment_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :weight, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :weight, :class => "input-xlarge" %>
      <p class="help-block">Weight of aircraft</p>
    </div>
  </div>
  <div class="field">
    <%= f.label :moment, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :moment, :class => "input-xlarge" %>
      <p class="help-block">Moment of aircraft</p>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
    <%= link_to "Cancel", aircraft_path(@aircraft), :class => "btn" %>
  </div>
<% end %>

app/views/moment_entries/edit.html.erb
<h1>Editing moment_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @moment_entry %> |
<%= link_to 'Back', moment_entries_path %>

app/views/moment_entries/index.html.erb
<h1>Listing moment_entries</h1>

<table>
  <tr>
    <th>Weight</th>
    <th>Moment</th>
    <th>Aircraft</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @moment_entries.each do |moment_entry| %>
  <tr>
    <td><%= moment_entry.weight %></td>
    <td><%= moment_entry.moment %></td>
    <td><%= moment_entry.aircraft_id %></td>
    <td><%= link_to 'Show', moment_entry %></td>
    <td><%= link_to 'Edit', edit_moment_entry_path(moment_entry) %></td>
    <td><%= link_to 'Destroy', moment_entry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Moment entry', new_moment_entry_path %>

app/views/moment_entries/new.html.erb
<fieldset>
  <legend>New Moment Entry</legend>
  <%= render 'form' %>
</fieldset>

<%= link_to 'Back', moment_entries_path %>

app/views/moment_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Weight:</b>
  <%= @moment_entry.weight %>
</p>

<p>
  <b>Moment:</b>
  <%= @moment_entry.moment %>
</p>

<p>
  <b>Aircraft:</b>
  <%= @moment_entry.aircraft_id %>
</p>


<%= link_to 'Edit', edit_moment_entry_path(@moment_entry) %> |
<%= link_to 'Back', moment_entries_path %>